### ISSUE TITLE
Corrections to eventseg_analysis.ipynb

### ISSUE THREAD

**Issue by cbaldassano** [ContextLab/sherlock-topic-model-paper#36]
This repository is awesome, I am enjoying going through the analyses! One issue I've run into is that the 4th code cell in eventseg_analysis.ipynb doesn't run. I got it to run with 2 fixes:
1) Changing "import brainiak.eventseg.event" to "import brainiak.eventseg.event as event"
2) Changing "movie_model" to "video_model"

Is that correct?

**Comment by andrewheusser** [comment]
hey @cbaldassano, thanks for the feedback! `movie_model` should be `video_model`. I searched the notebook and found one instance that needs to be updated.  Re the import statement, not sure why that isn't working, but perhaps the package structure has been updated recently? That's the syntax used in your brainiak example: https://github.com/brainiak/brainiak/blob/master/examples/eventseg/HiddenMarkovModels.ipynb so it seems like it should work unless there are some recent changes

**Comment by cbaldassano** [comment]
Thanks Andy. For the import statement, it is a scoping issue - in my brainiak example, I later create the EventSegment object as 

brainiak.eventseg.event.EventSegment

while you are using

event.EventSegment

So either you need to change this to include the full package path, or change the import statement. I am testing this in your docker instance, so we should be using the same versions of everything - are you able to run this cell without that change?

**Comment by andrewheusser** [comment]
Ah - good point.  I'm not able to test it at the moment.  @paxtonfitzpatrick - any chance you can run the script as is inside our Docker and see if it works?  I'm guessing that it won't work, and that I introduced this in a final cleanup stage, but then forgot to rerun the full notebook.

If it works as it is, we can revisit this thread but otherwise, I think @paxtonfitzpatrick can just merge in your edits.

Thanks @cbaldassano!

**Comment by paxtonfitzpatrick** [comment]
Just merged in the fixes

Thanks @cbaldassano!
