### ISSUE TITLE
Length of embeddings and mappings don't match for subj 6

### ISSUE THREAD

**Issue by cbaldassano** [ContextLab/sherlock-topic-model-paper#37]
The notebook trajectory_analysis_and_fig.ipynb crashes on the last cell, and I believe the reason is because embeddings[6] and mappings[6] don't have the same number of events in the saved npy files (one is 17, the other is 11)

In [2]: e = np.load('../../../data/processed/embeddings.npy')
In [3]: m = np.load('../../../data/processed/labels.npy')
In [4]: [i.shape[0] for i in e]
Out[4]: [8, 14, 11, 9, 14, 10, 17, 17, 10, 20, 19, 25, 27, 14, 10, 14, 23, 34, 34]
In [5]: [i.shape[0] for i in m]
Out[5]: [8, 14, 11, 9, 14, 10, 11, 17, 10, 21, 19, 25, 27, 14, 10, 14, 23]

Maybe subject 6 accidentally got overwritten with subject 7 in embeddings.npy?

**Comment by andrewheusser** [comment]
hmmm, I think the issue is that labels.npy must be the wrong file. P7 (embeddings[6]) and and P8 (embeddings[7]) should both have 17 events as displayed in this figure: 

https://github.com/ContextLab/sherlock-topic-model-paper/blob/master/paper/figs/corrmats.pdf

i'll fix this when i get a chance and ping you when its fixed!

**Comment by jeremymanning** [comment]
@cbaldassano cool, and we'll try to get these updated before your lab meeting!  thanks for going through these so carefully!

**Comment by andrewheusser** [comment]
@cbaldassano - fixed the labels on this commit: 4f77750c436264585879efb9f91957dc555f36a9

When you get a chance, please let me know if it fixes the issue on your end!
